import {defineConfig, type Plugin} from 'vite'
import {resolve} from 'path'
import {readFileSync, writeFileSync} from 'fs'
import dts from 'vite-plugin-dts'

const packageManifest = JSON.parse(readFileSync(resolve(__dirname, 'package.json'), 'utf-8'))

/**
 * Prepend the activation runtime (`honey-activation-runtime.{js,cjs}`) to
 * every non-bootstrap dist entry. The runtime checks `window.__HONEY_ACTIVATED__`
 * and logs a one-shot console warning when the install is unregistered. The
 * runtime file itself is regenerated by `scripts/honey-postinstall.mjs` on
 * `npm install` and by `bin/honey.js activate` after a successful POST to the
 * licensing backend, so the warning state stays in sync with the project's
 * registered status without rebuilding the package.
 *
 * Generates a baseline inactive runtime here so a clean build (without a
 * postinstall step having run) still has the file on disk and entries still
 * resolve their imports.
 */
function honeyActivationInject(entryNames: string[]): Plugin {
    return {
        name: 'honey-activation-inject',
        apply: 'build',
        closeBundle() {
            const distDir = resolve(__dirname, 'dist')

            const warningMessage = JSON.stringify(
                [
                    '[Honey] This project is using @banzamel/honey, but the installation is not registered yet.',
                    'Run `node ./node_modules/@banzamel/honey/bin/honey.js activate --license-key=YOUR_LICENSE_KEY` to register this project in your license portal.',
                    'Honey will keep working without activation, but premium backend features (audit logging, cross-domain consent sharing, server-side scan reports) need a registered install.',
                ].join(' ')
            )

            const inactiveState = {
                activated: false,
                packageName: packageManifest.name,
                packageVersion: packageManifest.version ?? null,
                projectName: null,
                environment: null,
                hostname: null,
                instanceId: null,
                activationId: null,
                activatedAt: null,
                apiBaseUrl: 'https://api.mineralui.io',
            }

            const runtimes = [
                {
                    file: 'honey-activation-runtime.js',
                    include: (file: string) => `${file}.js`,
                    prefix: "import './honey-activation-runtime.js'\n",
                    code: [
                        `const activationState=${JSON.stringify(inactiveState)}`,
                        'function applyHoneyActivationState(){',
                        'if(typeof window==="undefined"){return}',
                        'if(activationState.activated){window.__HONEY_ACTIVATED__=true;return}',
                        'if(window.__HONEY_ACTIVATION_WARNING_SHOWN__===true){return}',
                        'window.__HONEY_ACTIVATION_WARNING_SHOWN__=true',
                        `console.warn(${warningMessage})`,
                        '}',
                        'applyHoneyActivationState()',
                        'export {activationState,applyHoneyActivationState}',
                    ].join('\n'),
                },
                {
                    file: 'honey-activation-runtime.cjs',
                    include: (file: string) => `${file}.cjs`,
                    prefix: "require('./honey-activation-runtime.cjs')\n",
                    code: [
                        `const activationState=${JSON.stringify(inactiveState)}`,
                        'function applyHoneyActivationState(){',
                        'if(typeof window==="undefined"){return}',
                        'if(activationState.activated){window.__HONEY_ACTIVATED__=true;return}',
                        'if(window.__HONEY_ACTIVATION_WARNING_SHOWN__===true){return}',
                        'window.__HONEY_ACTIVATION_WARNING_SHOWN__=true',
                        `console.warn(${warningMessage})`,
                        '}',
                        'applyHoneyActivationState()',
                        'exports.activationState=activationState',
                        'exports.applyHoneyActivationState=applyHoneyActivationState',
                    ].join('\n'),
                },
            ]

            for (const runtime of runtimes) {
                writeFileSync(resolve(distDir, runtime.file), runtime.code)
                for (const entryName of entryNames) {
                    const entryPath = resolve(distDir, runtime.include(entryName))
                    try {
                        const code = readFileSync(entryPath, 'utf-8')
                        if (!code.includes(runtime.prefix.trim())) {
                            writeFileSync(entryPath, runtime.prefix + code)
                        }
                    } catch {
                        /* skip if file doesn't exist */
                    }
                }
            }
        },
    }
}

/**
 * Auto-injects the built CSS into the JS entry on first import, so consumers
 * get fully styled components without an explicit `import '@banzamel/honey/styles.css'`.
 * The styles can still be imported manually for SSR-only setups.
 */
function cssAutoInject(entryNames: string[]): Plugin {
    return {
        name: 'honey-css-auto-inject',
        apply: 'build',
        closeBundle() {
            const distDir = resolve(__dirname, 'dist')
            let css: string
            try {
                css = readFileSync(resolve(distDir, 'styles.css'), 'utf-8')
            } catch {
                return
            }

            const escaped = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')

            const runtimes = [
                {
                    file: 'style-runtime.js',
                    include: (file: string) => `${file}.js`,
                    prefix: "import {ensureStyles} from './style-runtime.js'\nensureStyles()\n",
                    code: [
                        'export function ensureStyles(){',
                        'if(typeof document!=="undefined"){',
                        'let s=document.getElementById("honey-styles");',
                        'if(!s){s=document.createElement("style");',
                        's.id="honey-styles";',
                        `s.textContent=\`${escaped}\`;`,
                        'document.head.appendChild(s)}}',
                        '}',
                    ].join(''),
                },
                {
                    file: 'style-runtime.cjs',
                    include: (file: string) => `${file}.cjs`,
                    prefix: "const {ensureStyles}=require('./style-runtime.cjs')\nensureStyles()\n",
                    code: [
                        'function ensureStyles(){',
                        'if(typeof document!=="undefined"){',
                        'let s=document.getElementById("honey-styles");',
                        'if(!s){s=document.createElement("style");',
                        's.id="honey-styles";',
                        `s.textContent=\`${escaped}\`;`,
                        'document.head.appendChild(s)}}',
                        '}',
                        'exports.ensureStyles=ensureStyles',
                    ].join(''),
                },
            ]

            for (const runtime of runtimes) {
                writeFileSync(resolve(distDir, runtime.file), runtime.code)
                for (const entryName of entryNames) {
                    const entryPath = resolve(distDir, runtime.include(entryName))
                    try {
                        const code = readFileSync(entryPath, 'utf-8')
                        if (!code.startsWith(runtime.prefix)) {
                            writeFileSync(entryPath, runtime.prefix + code)
                        }
                    } catch {
                        /* skip if file doesn't exist */
                    }
                }
            }
        },
    }
}

const entryMap = {
    index: resolve(__dirname, 'src/index.ts'),
    'cookie-consent-bootstrap': resolve(__dirname, 'src/cookie-consent-bootstrap.ts'),
}

// The bootstrap entry runs before any React/CSS is loaded — it must not pull
// in styles or trigger the auto-inject runtime, and it must not surface the
// activation warning either (the loader script attaches to the page before
// `<script src="…/index.js">` runs and we don't want to nag twice).
const reactFacingEntries = Object.keys(entryMap).filter(
    (entryName) => entryName !== 'cookie-consent-bootstrap'
)

export default defineConfig({
    plugins: [
        dts({insertTypesEntry: true, rollupTypes: false}),
        cssAutoInject(reactFacingEntries),
        honeyActivationInject(reactFacingEntries),
    ],
    build: {
        lib: {
            entry: entryMap,
            name: 'Honey',
            formats: ['es', 'cjs'],
            fileName: (format, entryName) => `${entryName}.${format === 'es' ? 'js' : 'cjs'}`,
        },
        rollupOptions: {
            external: ['react', 'react-dom', 'react/jsx-runtime'],
            output: {
                globals: {
                    react: 'React',
                    'react-dom': 'ReactDOM',
                    'react/jsx-runtime': 'jsxRuntime',
                },
                assetFileNames: 'styles.css',
            },
        },
        cssCodeSplit: false,
        sourcemap: true,
    },
})
