/**
 * Snapshot of the install's licensing state. Generated by either:
 * - `scripts/honey-postinstall.mjs` on `npm install` (inactive baseline when no
 *   prior activation, regenerated from `.honey/activation.json` when present)
 * - `bin/honey.js activate --license-key=…` after a successful licensing POST
 *
 * The dist runtime sets `window.__HONEY_ACTIVATED__ = true` when this state's
 * `activated` is true, and otherwise logs a one-shot console warning. The
 * package itself never gates rendering on activation — cookie consent is a
 * legal requirement and we don't paywall it. The license unlocks backend
 * features (audit logging, cross-domain consent, hosted scan reports).
 *
 * Consumers can read `getHoneyActivationState()` to render their own admin UI
 * showing license status. The shape mirrors what the dist runtime writes so a
 * single read returns either the inactive baseline (when no postinstall ran)
 * or the live state from the previous activation.
 */
export interface HoneyActivationState {
    activated: boolean
    packageName: string
    packageVersion: string | null
    projectName: string | null
    environment: string | null
    hostname: string | null
    instanceId: string | null
    activationId: string | null
    activatedAt: string | null
    apiBaseUrl: string
}

const INACTIVE_FALLBACK: HoneyActivationState = {
    activated: false,
    packageName: '@banzamel/honey',
    packageVersion: null,
    projectName: null,
    environment: null,
    hostname: null,
    instanceId: null,
    activationId: null,
    activatedAt: null,
    apiBaseUrl: 'https://api.mineralui.io',
}

/**
 * Whether this install is registered with the Honey licensing backend.
 * Returns `false` in non-browser contexts (SSR, scripts) — the runtime only
 * exposes the flag on `window`.
 */
export function isHoneyActivated(): boolean {
    if (typeof window === 'undefined') {
        return false
    }

    return window.__HONEY_ACTIVATED__ === true
}

/**
 * Return the current activation snapshot if the runtime is available, or the
 * inactive fallback otherwise. The actual rich state (instanceId, activationId,
 * activatedAt, hostname) lives in the dist runtime module — read it directly
 * from `dist/honey-activation-runtime.js` if you need more than the activated
 * flag inside Node tooling.
 */
export function getHoneyActivationState(): HoneyActivationState {
    if (typeof window === 'undefined') {
        return INACTIVE_FALLBACK
    }

    return {
        ...INACTIVE_FALLBACK,
        activated: window.__HONEY_ACTIVATED__ === true,
    }
}

declare global {
    interface Window {
        __HONEY_ACTIVATED__?: boolean
        __HONEY_ACTIVATION_WARNING_SHOWN__?: boolean
    }
}
